INSERT into linksport.gender values (1, "Homme");
INSERT into linksport.gender values (2, "Femme");

INSERT into linksport.role values (1, "ROLE_ADMIN");
INSERT into linksport.role values (2, "ROLE_PLAYER");
INSERT into linksport.role values (3, "ROLE_COACH");
INSERT into linksport.role values (4, "ROLE_TEAM");

insert into linksport.sport values (1, "Football");
insert into linksport.sport values (2, "Basketball");
insert into linksport.sport values (3, "Handball");

insert into linksport.level values (1, "Ligue 1", 1);
insert into linksport.level values (2, "Ligue 2", 1);
insert into linksport.level values (3, "National", 1);
insert into linksport.level values (4, "National 2", 1);
insert into linksport.level values (5, "National 3", 1);
insert into linksport.level values (6, "Regional 1", 1);
insert into linksport.level values (7, "Regional 2", 1);
insert into linksport.level values (8, "Regional 3", 1);
insert into linksport.level values (9, "Départemental 1", 1);
insert into linksport.level values (10, "Départemental 2", 1);
insert into linksport.level values (11, "Départemental 3", 1);
insert into linksport.level values (12, "Départemental 4", 1);
insert into linksport.level values (13, "Départemental 5", 1);
insert into linksport.level values (14, "Pro A", 2);
insert into linksport.level values (15, "Pro B", 2);
insert into linksport.level values (16, "National 1", 2);
insert into linksport.level values (17,"National 2",2);
insert into linksport.level values (18,"National 3",2);
insert into linksport.level values (19,"Pré-national",2);
insert into linksport.level values (20,"Régional 2",2);
insert into linksport.level values (21,"Régional 3",2);
insert into linksport.level values (22,"Pré-régional",2);
insert into linksport.level values (23,"Départemental 2",2);
insert into linksport.level values (24,"Départemental 3",2);
insert into linksport.level values (25,"Division 1 (Starligue)",3);
insert into linksport.level values (26,"Division 2 (Proligue)",3);
insert into linksport.level values (27,"National 1",3);
insert into linksport.level values (28,"National 2",3);
insert into linksport.level values (29,"National 3",3);
insert into linksport.level values (30,"Pré-national",3);
insert into linksport.level values (31,"Excellence régional",3);
insert into linksport.level values (32,"Honneur régional",3);
insert into linksport.level values (33,"Pré-régional",3);
insert into linksport.level values (34,"Excellence départemental",3);
insert into linksport.level values (35,"Honneur départemental",3);

INSERT INTO linksport.position VALUES (1, "Gardien", 1);
INSERT INTO linksport.position VALUES (2, "Défenseur Central", 1);
INSERT INTO linksport.position VALUES (3, "Défenseur Gauche", 1);
INSERT INTO linksport.position VALUES (4, "Défenseur Droit", 1);
INSERT INTO linksport.position VALUES (5, "Milieu Défensif", 1);
INSERT INTO linksport.position VALUES (6, "Milieu Relayeur", 1);
INSERT INTO linksport.position VALUES (7, "Milieu Offensif", 1);
INSERT INTO linksport.position VALUES (8, "Milieu Droit", 1);
INSERT INTO linksport.position VALUES (9, "Milieu gauche", 1);
INSERT INTO linksport.position VALUES (10, "Buteur", 1);
INSERT INTO linksport.position VALUES (11, "Attaquant", 1);
INSERT INTO linksport.position VALUES (12, "Attaquant Droit", 1);
INSERT INTO linksport.position VALUES (13, "Attaquant Gauche", 1);
INSERT INTO linksport.position VALUES (14, "Meneur", 2);
INSERT INTO linksport.position VALUES (15, "Arrière", 2);
INSERT INTO linksport.position VALUES (16, "Ailier", 2);
INSERT INTO linksport.position VALUES (17, "Ailier Fort", 2);
INSERT INTO linksport.position VALUES (18, "Pivot", 2);
INSERT INTO linksport.position VALUES (19, "Ailier Gauche", 3);
INSERT INTO linksport.position VALUES (20, "Ailier Droit", 3);
INSERT INTO linksport.position VALUES (21, "Arrière Gauche", 3);
INSERT INTO linksport.position VALUES (22, "Arriére Droit", 3);
INSERT INTO linksport.position VALUES (23, "Demi-centre", 3);
INSERT INTO linksport.position VALUES (24, "Pivot", 3);
INSERT INTO linksport.position VALUES (25, "Gardien", 3);